name: Build ARM64 RootFS Image

on:
  workflow_dispatch:

jobs:
  build-arm64-rootfs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU for multi-arch
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build ARM64 Docker image
      run: |
        docker buildx build --platform linux/arm64 -t my-ubuntu-arm64:20.04 -f Dockerfile.arm64 .

    - name: Export rootfs tar
      run: |
        container_id=$(docker create my-ubuntu-arm64:20.04)
        docker export $container_id > rootfs.tar
        docker rm $container_id

    - name: Create ext4 image
      run: |
        dd if=/dev/zero of=ubuntu_rootfs.img bs=1M count=6144
        mkfs.ext4 ubuntu_rootfs.img
        mkdir mnt
        sudo mount ubuntu_rootfs.img mnt
        sudo tar -xpf rootfs.tar -C mnt
        sudo umount mnt
        ls -lh ubuntu_rootfs.img

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu_rootfs_img
        path: ubuntu_rootfs.img
